### ISSUE TITLE
Can´t access to OneDrive with mDriveOOo extension

### ISSUE THREAD

**Issue by Fa5g** [prrvchr/mDriveOOo#10] opened 2023-08-23 02:01 UTC
Even though I have installed the three extensions indicated in your tutorial: **OAuth2OOo.oxt, jdbcDriverOOo.oxt, mDriveOOo.oxt**, I have not been able to get the corresponding access to OpenDrive to create, edit and then save my files. I´m using Ubuntu 22.04.3 LTS and LibreOffice 7.5.5.2. When running in terminal the command soffice as was suggested at https://github.com/prrvchr/mDriveOOo/issues/9#issuecomment-1687750107, LibreOffice open and show its main screen, no errors at all. Maybe I´m doing something wrong! Any help would be highly appreciated. Thanks.

**Comment by Fa5g** [comment] 2023-08-23 03:13
> Even though I have installed the three extensions indicated in your tutorial: **OAuth2OOo.oxt, jdbcDriverOOo.oxt, mDriveOOo.oxt**, I have not been able to get the corresponding access to OpenDrive to create, edit and then save my files. I´m using Ubuntu 22.04.3 LTS and LibreOffice 7.5.5.2. When running in terminal the command soffice as was suggested at [#9 (comment)](https://github.com/prrvchr/mDriveOOo/issues/9#issuecomment-1687750107), LibreOffice open and show its main screen, no errors at all. Maybe I´m doing something wrong! Any help would be highly appreciated. Thanks.

I tried putting vnd-microsoft://xxxxx@live.com on the first drop-down, nothing happens on the LibreOffice screen, the terminal show the following: 

xxxx@xxxxxxx:~$ soffice
ContentProvider.__init__()
LoggerPool.__init__() *******************************
LoggerPool._getNamedLogger() io.github.prrvchr.mDriveOOo.mDriveLog
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9

**Comment by prrvchr** [comment] 2023-08-23 09:40
The first thing to do, but you may have already done it?

- check in: **Tools -> Options -> LibreOffice -> Advanced** that a version **11 of Java** appears in the list and is selected.
- check the version of the HsqlDB driver in: **Tools -> Options -> Base drivers -> JDBC drivers -> JDBC drivers settings -> Embedded drivers -> jdbc:hsqldb:*** is 2.7.2
- **uninstall** the three extensions.
- **restart** LibreOffice.
- **reinstall** the three extensions with the console open to see any error messages.

**Comment by Fa5g** [comment] 2023-08-23 16:14
I did the following:
- Checked the versions on Tools as JRE Version 11.0.20 and HsqlDB driver is 2.7.2
- Uninstalled the three extensions
- Restarted LibreOffice
- Reinstalled the three extensions again with terminal open, the OneDrive extension didn´t work, wrote down the vnd-microsoft on 1st drop-down and nothing happens.
- Run the Tools/Options/Internet/oAuth Wizard and ckecked the mDriveOOo on it trying different OneDriveOOo settings
- The situation is the same. 
- The Terminal log was as below:
xxxx@xxxxxxx:~$ soffice
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
ContentProvider.__init__()
LoggerPool.__init__() *******************************
LoggerPool._getNamedLogger() io.github.prrvchr.mDriveOOo.mDriveLog
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
OptionsHandler.__init__() 1
OptionsHandler.__init__() 2
LoggerPool.__init__() *******************************
LoggerPool._getNamedLogger() io.github.prrvchr.OAuth2OOo.OAuth2Logger
LoggerPool.__init__() *******************************
OAuth2Service.__init__() 1
LoggerPool.__init__() *******************************
LoggerPool.__init__() *******************************
OAuth2Service.__init__() 2
Wizard.__init__()
LoggerPool.__init__() *******************************
OAuth2Model._getCodeChallenge() 1
OAuth2Model._getCodeChallenge() 2
Gtk-Message: 09:39:39.164: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
OAuth2Model._getCodeChallenge() 1
OAuth2Model._getCodeChallenge() 2
LoggerPool.__init__() *******************************
LoggerPool.__init__() *******************************
Gtk-Message: 09:39:49.778: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
OAuth2Model._getResponseFromRequest() Url: https://login.microsoftonline.com/common/oauth2/v2.0/token - Data: {'code': 'M.C106_BAY.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'grant_type': 'authorization_code', 'client_id': 'ccaf8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'redirect_uri': 'http://localhost:8080/', 'code_verifier': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'scope': 'offline_access user.read Files.ReadWrite.All'} - Timeout: (5, 30)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'login.microsoftonline.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
WizardController.createPage() 1
OAuth2View.__init__() 1
OAuth2View.__init__() 2
WizardController.createPage() 2
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9
ContentProvider.__init__() 1 Scheme: vnd-microsoft
ContentProvider.__init__() 2 Scheme: vnd-microsoft
DataSource._getDataSource() 1
DataSource._getDataSource() 2
DataSource._getDataSource() 5
DataSource._getDataSource() 6
DataSource._getDataSource() 7
DataSource._getDataSource() 9

**Comment by prrvchr** [comment] 2023-08-23 18:22
I would like to point out that the **Open button does not work**, you must enter the connection url and validate with the **enter key**

**Comment by Fa5g** [comment] 2023-08-23 19:35
I did it like this and it doesn't work either

**Comment by prrvchr** [comment] 2023-08-24 11:23
Apart from the log view that you bring me, it seems that the problem is related to the connection to the HsqlDB database.

First you have to try again with the new version of OAuth2OOo and mDriveOOo.

I suspect a problem in the user profile, it would be good to delete the folder: /home/user/.config/libreoffice and make a copy beforehand in order to be able to restore it if necessary...

Last thing to check is the version of the python modules which is accessible in:
**Tools -> Options -> Internet -> OAuth2 protocol -> View log -> System info**
You must first enable logging and restart LibreOffice for this to take effect.

**Comment by Fa5g** [comment] 2023-08-25 03:49
I followed the above steps resulting the same issue! Also deleted the profile in home/user/.config/libreoffice and no changes. At the end you can find the logs.
![Screenshot from 2023-08-24 21-10-59](https://github.com/prrvchr/mDriveOOo/assets/4894803/f493fa52-da36-4414-802c-e2ca908ed22f)
![Screenshot from 2023-08-24 21-10-44](https://github.com/prrvchr/mDriveOOo/assets/4894803/c63a1e97-ca1b-4a28-b6fc-f7b986644275)

[soffice-log.txt](https://github.com/prrvchr/mDriveOOo/files/12435241/soffice-log.txt)

[oAuth-log.txt](https://github.com/prrvchr/mDriveOOo/files/12435322/oAuth-log.txt)

**Comment by prrvchr** [comment] 2023-08-27 18:33
Looking at the log files it seems that the mDriveOOo database is not created during the first connection.

I would like to see the jdbc driver version loaded by jdbcDriverOOo.

First you must install the latest version of [jdbcDriverOOo 1.0.5](https://prrvchr.github.io/jdbcDriverOOo/) which allows to record the version of the JDBC drivers in the log file.

After, can you go to:
**Tools -> Options -> Base drivers -> JDBC driver -> JDBC driver settings**

And after make a copy of the log file which can be accessed by:
**Tools -> Options -> Base drivers -> JDBC driver -> UNO driver settings -> View log**

**Comment by Fa5g** [comment] 2023-08-28 01:49
Find the log at the end.

![Screenshot from 2023-08-27 19-43-06](https://github.com/prrvchr/mDriveOOo/assets/4894803/a243b69a-259a-439b-9c4b-fa7b3f78c89a)

![Screenshot from 2023-08-27 19-41-58](https://github.com/prrvchr/mDriveOOo/assets/4894803/9338f74a-05a6-4ad9-a571-334e0083dab2)

[jdbc-driver-log.txt](https://github.com/prrvchr/mDriveOOo/files/12449484/jdbc-driver-log.txt)

**Comment by prrvchr** [comment] 2023-09-06 10:55
Okay, I'm seriously lacking ideas regarding this problem...

Could you show me what is displayed in:
**Tools -> Options -> LibreOffice Base -> Connections and Databases**

**Comment by Fa5g** [comment] 2023-09-06 22:11
I tried connection pooling enabled and enable pooling for this driver (com.sun.star.comp.sdbc.JDBCDriver) also and nothing happens, the issue is the same.
![Screenshot from 2023-09-06 14-22-48](https://github.com/prrvchr/mDriveOOo/assets/4894803/958d0223-3c96-4478-9ee1-8da03b3c494e)
![Screenshot from 2023-09-06 14-23-03](https://github.com/prrvchr/mDriveOOo/assets/4894803/861cc714-4347-4f6f-9430-a0d39df52daf)

**Comment by prrvchr** [comment] 2023-09-07 10:20
I suspect that the database is not being created on the first launch of the **mDriveOOo** extension.

An **vnd-microsoft.odb** file is created during this first launch in the folder:
**~userprofile/libreoffice/4/user/uno_packages/cache/uno_packages/luXXXXXXXXXXXX.tmp_/mDriveOOo.oxt/hsqldb**

Can you confirm the presence of this file?
If it is not there, I will trace in the logging more precisely the code allowing the creation of this odb file.

**Comment by Fa5g** [comment] 2023-09-07 19:31
There file  vnd-microsoft.odb isn't listed in the directory only the followings:
xxxx@xxxx:~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu55361aq9m.tmp_/mDriveOOo.oxt/hsqldb$ ls -l
total 1572
-rw-rw-r-- 1 xxxx xxxx     261 sep  6 16:02 Columns.csv
-rw-rw-r-- 1 xxxx xxxx 1592533 sep  6 16:02 hsqldb.jar
-rw-rw-r-- 1 xxxx xxxx     337 sep  6 16:02 Settings.csv
-rw-rw-r-- 1 xxxx xxxx    1657 sep  6 16:02 TableColumn.csv
-rw-rw-r-- 1 xxxx xxxx     129 sep  6 16:02 Tables.csv

And the driver io.github.prrvchr.uno.sdbcx.Driver isn´t listed on Options - LibreOffice Base - Connections either.

**Comment by prrvchr** [comment] 2023-09-12 08:37
I just updated mDriveOOo.
This update makes it possible to log the creation of the database during the first connection.

Here is the log obtained during my first connection:
`  event no thread   date       time        (class/method:) message
         1     7234 2023-09-12 08:25:41.865355436 ContentProvider::__init__(): ContentProvider: io.github.prrvchr.mDriveOOo.NamedProvider Loading completed
         2     7234 2023-09-12 08:25:41.887685901 DataSource::_getDataSource(): Try to create a new data source with the URL: file:///home/prrvchr/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu7023pj63.tmp_/mDriveOOo.oxt/hsqldb/vnd-microsoft.odb
         3     7234 2023-09-12 08:25:41.896514304 DataSource::_getDataSource(): A new data source has been created with the URL: file:///home/prrvchr/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu7023pj63.tmp_/mDriveOOo.oxt/hsqldb/vnd-microsoft.odb
         4     7234 2023-09-12 08:25:43.976645569 DataBase::__init__(): DataBase: Loading completed
         5     7234 2023-09-12 08:25:44.060081650 DataBase::createDataBase(): Try to create the database with HsqlDB version: 2.7.2
         6     7234 2023-09-12 08:25:48.047168324 DataBase::createDataBase(): Successful database creation
         7     7234 2023-09-12 08:25:48.391061406 DataSource::__init__(): DataSource: Loading completed
         8     7234 2023-09-12 08:25:48.393041235 NamedContentProvider::__init__(): ParameterizedProviderNamed Loading completed
         9     7234 2023-09-12 08:25:48.394889198 NamedContentProvider::createContentIdentifier(): Identifier: vnd-microsoft://prrvchr@gmail.com/ -> vnd-microsoft://prrvchr@gmail.com/
        10     7234 2023-09-12 08:25:55.307353780 DataBase::__init__(): DataBase: Loading completed
        11     7234 2023-09-12 08:25:55.451503023 Content::__init__(): Content loading completed
        12     7234 2023-09-12 08:25:55.455238154 ContentUser::__init__(): ContentUser loading completed
        13     7234 2023-09-12 08:25:55.457692547 NamedContentProvider::queryContent(): Identitifer: vnd-microsoft://prrvchr@gmail.com/ ... Completed
        14     7234 2023-09-12 08:25:55.460855772 Content::execute(): command.Name: open
        15     7234 2023-09-12 08:25:56.049137845 Content::_updateFolderContent(): The content of the folder:  is obtained with Request!!!
        16     7234 2023-09-12 08:25:56.967740140 Content::execute(): command.Name: open IsFolder: True
        17     7234 2023-09-12 08:25:57.247404574 NamedContentProvider::createContentIdentifier(): Identifier: vnd-microsoft://prrvchr@gmail.com/ -> vnd-microsoft://prrvchr@gmail.com/
        18     7234 2023-09-12 08:25:57.249749087 NamedContentProvider::queryContent(): Identitifer: vnd-microsoft://prrvchr@gmail.com/ ... Completed
        19     7234 2023-09-12 08:25:57.252278296 Content::execute(): command.Name: getPropertyValues
        20     7234 2023-09-12 08:25:57.254098372 Content::_getPropertiesValues(): ERROR: Requested property: CreatableContentsInfo is not available`

On the other hand, it is not normal that the jdbcDriverOOo driver is not listed in: **Options -> LibreOffice Base -> Connections**

Here is the screenshot I get after installing jdbcDriverOOo:
![Connection Pool](https://github.com/prrvchr/mDriveOOo/assets/7834336/08cafdae-1201-4b42-ba7e-1b535ac8e952)

Here is my about LibreOffice:
![About LibreOffice](https://github.com/prrvchr/mDriveOOo/assets/7834336/b92910f0-ac72-486a-a1af-f7406c8ca7a3)

**Comment by Fa5g** [comment] 2023-09-12 20:02
I uninstalled the three extensions, downloaded and installed again. I noticed the jdbcDriverOOo.jar driver is listed in the directory ~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu263512ch1f.tmp_/jdbcDriverOOo.oxt/, but not in the ~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu263512ch1f.tmp_/jdbcDriverOOo.oxt/driver/ directory where all the others that come with LibreOffice are, see screenshots. Perhaps for this reason this driver is not listed in Options - LibreOffice Base - Connections, I tried to copy the .jar file into the LibreOffice driver directory and it doesn't work either. It is a shame that this useful extension has not yet been able to work in LibreOffice, perhaps by identifying the reason why the jdbcDriverOOo is not installed correctly, you will be able to solve it. The log file is attached also.

![Screenshot from 2023-09-12 13-33-06](https://github.com/prrvchr/mDriveOOo/assets/4894803/38244418-8244-4760-9ce4-a8f115abdf8f)
![Screenshot from 2023-09-12 13-33-21](https://github.com/prrvchr/mDriveOOo/assets/4894803/8abc5970-4f12-43a4-8f8e-7e80e7cf551c)

[io.github.prrvchr.jdbcDriverOOo.Driver.log](https://github.com/prrvchr/mDriveOOo/files/12590385/io.github.prrvchr.jdbcDriverOOo.Driver.log)

**Comment by prrvchr** [comment] 2023-09-12 20:21
>I noticed the jdbcDriverOOo.jar driver is listed in the directory ~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu263512ch1f.tmp_/jdbcDriverOOo.oxt/, but not in the ~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu263512ch1f.tmp_/jdbcDriverOOo.oxt/driver/ directory where all the others that come with LibreOffice are...

This is normal.
- jdbcDriverOOo.jar is the jar archive which contains all the UNO services necessary for the operation of the underlying Java JDBC drivers.
- the driver folder contains all the underlying Java JDBC drivers.

What is the log obtained during your first connection with mDriveOOo?

**Comment by Fa5g** [comment] 2023-09-12 22:05
After install **"sudo apt install libreoffice-base"** the **io.github.prrvchr.uno.sdbcx.Driver** appeared on **Options - LibreOffice Base - Connections**, but still experiencing the same issue. When try to create a new database the listed drivers are shown on the screenshot. The mDriveLog is attached also.
![Screenshot from 2023-09-12 15-45-31](https://github.com/prrvchr/mDriveOOo/assets/4894803/5f3f80d5-2653-449d-9331-0149c2b7bf1f)
![WhatsApp Image 2023-09-12 at 3 45 05 PM](https://github.com/prrvchr/mDriveOOo/assets/4894803/2f49670a-bd08-45ec-8593-734824db0efa)
[io.github.prrvchr.mDriveOOo.mDriveLog.log](https://github.com/prrvchr/mDriveOOo/files/12591170/io.github.prrvchr.mDriveOOo.mDriveLog.log)

**Comment by prrvchr** [comment] 2023-09-12 22:19
> After install "sudo apt install libreoffice-base" the io.github.prrvchr.uno.sdbcx.Driver appeared on Options - LibreOffice Base - Connections

for sure it can't work without this package...

You need to remove the following 2 packages and then it should work...

`sudo apt remove libreoffice-sdbc-hsqldb`
`sudo apt remove libhsqldb1.8.0-java`

Thank you to confirm.

**Comment by Fa5g** [comment] 2023-09-12 23:25
**libreoffice-sdbc-hsqldb** and **libhsqldb1.8.0-java** uninstalled, after OS reboot, tried writing **vnd-microsoft://**... on the 1st drop-down, nothing happens, resulting the same issue. The **io.github.prrvchr.uno.sdbcx.Driver** always appeared on Options - LibreOffice Base - Connections. Now the content on directory ~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu55361aq9m.tmp_/mDriveOOo.oxt/hsqldb is:

total 1584
-rw-rw-r-- 1 fasg fasg     261 sep 12 13:15 Columns.csv
-rw-rw-r-- 1 fasg fasg 1592533 sep 12 13:15 hsqldb.jar
-rw-rw-r-- 1 fasg fasg     337 sep 12 13:15 Settings.csv
-rw-rw-r-- 1 fasg fasg    1657 sep 12 13:15 TableColumn.csv
-rw-rw-r-- 1 fasg fasg     129 sep 12 13:15 Tables.csv
-rw-rw-r-- 1 fasg fasg     328 sep 12 16:07 vnd-microsoft.odb.log
-rw-rw-r-- 1 fasg fasg     420 sep 12 16:07 vnd-microsoft.odb.properties
-rw-rw-r-- 1 fasg fasg     101 sep 12 16:07 vnd-microsoft.odb.script

The vnd-microsoft.odb file is still missing.

[vnd-microsoft.odb.log](https://github.com/prrvchr/mDriveOOo/files/12591534/vnd-microsoft.odb.log)

**Comment by prrvchr** [comment] 2023-09-13 08:17
If you were missing the libreoffice-base package, I think your LibreOffice is not properly installed.
Try reinstalling LibreOffice and removing the 2 HsqlDB packages:

`sudo apt remove libreoffice`
`sudo apt autoremove`
`sudo apt install libreoffice`
`sudo apt remove libreoffice-sdbc-hsqldb`
`sudo apt remove libhsqldb1.8.0-java`

Reinstall the 3 extensions and making a copy of the mDrive log on first connection.

**Comment by Fa5g** [comment] 2023-09-14 02:06
Worked! but couldn't read the remote directories, the file box was blank, only was read the root directory, I tried writing the file name, enter and suddenly the LibreOffice closed, I uninstall and install the three drivers and worked again, but always can read the root remote directory only.

**Comment by prrvchr** [comment] 2023-09-14 02:40
Since the problems come from your configuration, I advise you, first of all, to try to create a new Microsoft oneDrive account, with an empty oneDrive, to ensure proper functioning.

**Comment by Fa5g** [comment] 2023-09-14 14:04
Tried with new account and other accounts, it seems the driver doesn't update the remote files and always open the local file list recovered the first time.

**Comment by prrvchr** [comment] 2023-10-31 18:16
Well I believe that this issue has nothing to do with mDriveOOo but rather is due to a bad installation of LibreOffice or even the system.
As I have no possibility of resolving these types of problems, I prefer to close this issue.

**Comment by prrvchr** [comment] 2024-01-06 09:50
Hi Fa5g,

I have just added a feature in the logs which allows you to list all the Python packages used by the extension, their origin (already installed on the system or provided by the extension) and their version (if it comes from the system).
This ensures that the Python configuration (except with Windows where Python comes with LibreOffice) is functional.

To use this new functionality, you must use the latest versions of OAuth2OOo 1.2.4, jdbcDriverOOo 1.0.8 and mDriveOOo 1.0.7

This information is available in the extension options dialog window: **Tools -> Options -> Internet -> Extension name -> View log -> System info**

**Comment by prrvchr** [comment] 2024-01-22 15:49
Well since **mDriveOOo version 1.1.0** allows you to install and/or upgrade Python packages with the `pip install requirements.txt` and/or `pip install --upgrade <package-name>` command, I allow myself to consider that this type of malfunction is resolved by this new functionality, so I close.

You are free to open a new one if necessary and thank you for your contribution.

**Closed by prrvchr** 2024-01-22 15:49 UTC
